### ISSUE TITLE
[Melhoria] Ajustar campo de nome e seleção de família

### ISSUE THREAD

**Issue by GuiMM** [leobri93/WarGame#6]
Centralizar os campos dentro do Bootstrap Well (http://getbootstrap.com/components/#wells)

**Comment by leobri93** [comment]
Dica: Mudar offset da coluna do bootstrap para que o campo se mexa para a direita, com isso ele ficara centralizado. 
Ex: 
![image](https://cloud.githubusercontent.com/assets/9899981/16233238/136aa870-37a4-11e6-9836-9d9ac0cb45ec.png)

**Comment by leobri93** [comment]
Resolvido por @GuiMM
